services:
 app:
  build: .
  image: jobapp:v3
  container_name: app
  environment:
   POSTGRES_URL: postgresql://postgres:password@postgres:5432/db
   REDIS_URL: redis://redis:6379
  ports:
   - "8000:8000"
  depends_on:
   - postgres
   - redis

 postgres:
  image: postgres:17
  container_name: postgres
  environment: 
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: password
   POSTGRES_DB: db
  ports:
   - "5432:5432"
  volumes:
   - postgres_data:/var/lib/postgresql/data

 redis:
  image: redis:7-alpine
  ports:
   - "6379:6379"
  volumes:
   - redis_data:/data
  
 publisher:
  image: jobapp:v3
  command: python publisher.py
  environment:
   POSTGRES_URL: postgresql://postgres:password@postgres:5432/db
   REDIS_URL: redis://redis:6379
   PYTHONUNBUFFERED: "1"
  depends_on:
   - postgres
   - redis

 worker:
  image: jobapp:v3
  command: python worker.py
  environment:
   POSTGRES_URL: postgresql://postgres:password@postgres:5432/db
   REDIS_URL: redis://redis:6379
   PYTHONUNBUFFERED: "1"
  depends_on:
   - postgres
   - redis



volumes:
 postgres_data:
 redis_data: 