apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: formalert

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      containers:
        - name: worker

          image: 185591434281.dkr.ecr.ap-south-1.amazonaws.com/jobapp:v3

          command:
            - python
            - worker.py

          env:
            - name: POSTGRES_URL
              value: postgresql://postgres:password@postgres:5432/db

            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: formalert-config
                  key: REDIS_URL

            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: formalert-config
                  key: PYTHONUNBUFFERED